nginx:
  image: nginx
  volumes:
    - ./deployment/dev/nginx.conf:/etc/nginx/nginx.conf
    - ./deployment/dev/devserver.conf:/etc/nginx/sites-enabled/devserver.conf
  ports:
    - "80:80"
    - "443:443"
app:
  build: .
  volumes:
    - .:/app
  ports:
    - "3000:3000"
    - "8021:8021"
    - "9001:9001"
  environment:
    - HOST_NAME=http://127.0.0.1
  env_file:
    - app.env
  links:
    - redis
    - mysql
    - mongo
redis:
  image: redis
  volumes:
    - ./deployment/dev/redis.conf:/usr/local/etc/redis/redis.conf
  ports:
    - "6379"
  command: redis-server /usr/local/etc/redis/redis.conf
mysql:
  image: mysql:5.7
  environment:
    - MYSQL_USER=dev
    - MYSQL_PASSWORD=dev
    - MYSQL_ROOT_PASSWORD=dev
    - MYSQL_DATABASE=gasapp
  ports:
    - "3306:3306"
mongo:
  image: mongo
  command: --smallfiles
  ports:
    - "27017"
